from dataclasses import dataclass


@dataclass
class Meters:
    total_cancelled_credits: str
    total_in: str
    total_out: str
    total_jackpot: str
    games_played: str
    games_won: str
    games_lost: str
    games_last_power_up: str
    games_last_slot_door_close: str
    slot_door_opened: str
    power_reset: str
    s1_bills_accepted: str
    s5_bills_accepted: str
    s10_bills_accepted: str
    s20_bills_accepted: str
    s50_bills_accepted: str
    s100_bills_accepted: str
    s500_bills_accepted: str
    s1000_bills_accepted: str
    s200_bills_accepted: str
    s25_bills_accepted: str
    s2000_bills_accepted: str
    s2500_bills_accepted: str
    s5000_bills_accepted: str
    s10000_bills_accepted: str
    s20000_bills_accepted: str
    s25000_bills_accepted: str
    s50000_bills_accepted: str
    s100000_bills_accepted: str
    s250_bills_accepted: str
    cashout_ticket_number: str
    cashout_amount_in_cents: str
    ascii_game_id: str
    ascii_additional_id: str
    bin_denomination: str
    bin_max_bet: str
    bin_progressive_mode: str
    bin_game_options: str
    ascii_paytable_id: str
    ascii_base_percentage: str
    bill_in_dollars: str
    ROM_signature: str
    current_credits: str
    bin_level: str
    amount: str
    partial_pay_amount: str
    bin_reset_id: str
    true_coin_in: str
    true_coin_out: str
    current_hopper_level: str
    credit_amount_of_all_bills_accepted: str
    coin_amount_accepted_from_external_coin_acceptor: str
    country_code: str
    bill_denomination: str
    meter_for_accepted_bills: str
    number_bills_in_stacker: str
    credits_sas_in_stacker: str
    machine_id: str
    sequence_number: str
    validation_type: str
    index_number: str
    date_validation_operation: str
    time_validation_operation: str
    validation_number: str
    ticket_amount: str
    ticket_number: str
    validation_system_id: str
    expiration_date_printed_on_ticket: str
    pool_id: str
    current_hopper_length: str
    current_hopper_status: str
    current_hopper_percent_full: str
    bin_validation_type: str
    total_validations: str
    cumulative_amount: str
    total_number_of_games_implemented: str
    game_n_number: str
    game_n_coin_in: str
    game_n_coin_out: str
    game_n_jackpot: str
    game_n_games_played: str
    game_n_number_config: str
    game_n_ascii_game_id: str
    game_n_ascii_additional_id: str
    game_n_bin_denomination: str
    game_n_bin_max_bet: str
    game_n_bin_progressive_group: str
    game_n_bin_game_options: str
    game_n_ascii_paytable_id: str
    game_n_ascii_base_percentage: str
    ascii_sas_version: str
    ascii_sas_number: str
    selected_game_number: str
    number_of_enabled_games: str
    enabled_game_numbers: str
    cashout_type: str
    cashout_amount: str
    ticket_status: str
    parsing_code: str
    validation_data: str
    registration_status: str
    asset_number: str
    registration_key: str
    pos_id: str
    game_lock_status: str
    available_transfers: str
    host_cashout_status: str
    aft_status: str
    max_buffer_index: str
    current_cashable_amount: str
    current_restricted_amount: str
    current_non_restricted_amount: str
    restricted_expiration: str
    restricted_pool_id: str
    game_number: str
    features: []
